version: "3"

# Just throw up some random passwords that will get reset in the container
services:
    postgresql:
        image: postgres:11.8
        environment:
            - POSTGRES_PASSWORD=6XjwVbNPqyFHUTdoXfV4DgEQV8B
            - POSTGRES_USERNAME=postgres
        restart: always
        ports:
            - 0.0.0.0:5432:5432
        volumes:
            - postgresql-data:/var/lib/postgresql/data

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=eUsSUuU73pUNyThBj3kB
            - MSSQL_PID=Developer
        restart: always
        ports:
            - 0.0.0.0:1433:1433
        volumes:
            - sql-server-data:/var/opt/mssql
        
volumes:
    postgresql-data:
    sql-server-data:
