version: "3.4"

# Just throw up some random passwords that will get reset in the container
services:

  postgresql:
    image: postgres:11.8
    environment:
      - POSTGRES_PASSWORD=6XjwVbNPqyFHUTdoXfV4DgEQV8B
      - POSTGRES_USERNAME=postgres
    restart: always
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 5s

  influx:
    image: influxdb:1.8.3
    environment:
      - INFLUXDB_DB=homeassistant
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=XkCMpC3i4G6a0K3L2u7U
      - INFLUXDB_USER=homeassistant_writer
      - INFLUXDB_USER_PASSWORD=gcOwVKQC9qoPzf06bnz4
      - INFLUXDB_READ_USER=homeassistant_reader
      - INFLUXDB_READ_USER_PASSWORD=WHZ480eXhv5HnbCPczAD
    restart: always
    ports:
      - 0.0.0.0:8088:8088
      - 0.0.0.0:8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb
      - influxdb-conf:/etc/influxdb

  grafana:
    image: grafana/grafana:7.3.4
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-etc:/etc/grafana
      - grafana-share:/usr/share/grafana

  garagedoor:
    image: swails/garagedoor:latest
    restart: always
    environment:
      - DATABASE_NAME=garagedoor
      - DATABASE_USER=garage
      - DATABASE_PASSWORD=b0337286-06d6-47b1-bead-a95e6275850c
      - DATABASE_SERVER=postgresql
      - SECRET_KEY=w6yq@17$hb@854&axxl3&3l7o+9vjl+3mpi0pqla5dg+rh%bx9
      - DEBUG=false
      - ALLOWED_HOSTS=localhost,garage.theswails.com,garage.jasonswails.com,192.168.1.55
    depends_on:
      - postgresql

  local-nginx:
    image: swails/qnap-nginx:aa876
    restart: always
    ports:
      - 0.0.0.0:8082:80

volumes:
  postgresql-data:
  influxdb-data:
  influxdb-conf:
  grafana-data:
  grafana-etc:
  grafana-share:
