version: "3"

# Just throw up some random passwords that will get reset in the container
services:

  postgresql:
    image: postgres:11.8
    environment:
      - POSTGRES_PASSWORD=6XjwVbNPqyFHUTdoXfV4DgEQV8B
      - POSTGRES_USERNAME=postgres
    restart: always
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]

  influx:
    image: influxdb:1.8.3
    environment:
      - INFLUXDB_DB=homeassistant
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=<INFLUX_ADMIN_PASSWORD>
      - INFLUXDB_USER=homeassistant_writer
      - INFLUXDB_USER_PASSWORD=<INFLUX_USER_PASSWORD>
      - INFLUXDB_READ_USER=homeassistant_reader
      - INFLUXDB_READ_USER_PASSWORD=<INFLUX_READER_PASSWORD>
    restart: always
    ports:
      - 0.0.0.0:8088:8088
      - 0.0.0.0:8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb
      - influxdb-conf:/etc/influxdb

  grafana:
    image: grafana/grafana:7.3.4
    restart: always
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-etc:/etc/grafana
      - grafana-share:/usr/share/grafana

  garagedoor:
    image: swails/garagedoor:latest
    restart: always
    environment:
      - DATABASE_NAME=garagedoor
      - DATABASE_USER=garage
      - DATABASE_PASSWORD=<dbpass>
      - DATABASE_SERVER=postgresql
      - SECRET_KEY=<secretkey>
      - DEBUG=false
      - ALLOWED_HOSTS="localhost,garage.theswails.com,garage.jasonswails.com,192.168.1.3"
    ports:
      - 0.0.0.0:8081:8081
    depends_on:
      - postgresql

volumes:
  postgresql-data:
  influxdb-data:
  influxdb-conf:
  grafana-data:
  grafana-etc:
  grafana-share:
