- hosts: "{{ varhosts | default('all') }}"
  tasks:
    - name: 'Check if reboot is required'
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Report if reboot is needed
      debug:
        msg: "Reboot is needed!"
      when:
        reboot_required_file.stat.exists
