- hosts: amber
  become: yes
  become_user: root
  tasks:
    - name: Install aptitude using apt
      apt:
        name: aptitude
        state: latest
        update_cache: yes
        force_apt_get: yes
    - name: Install required system packages
      apt:
        name: {{ item }}
        state: latest
        update_cache: yes
        loop:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Update apt and install docker-ce
      apt:
        update_cache: yes
        name: docker-ce
        state: latest

    - name: Add graphics drivers PPA
      apt_repository:
        repo: ppa:graphics-drivers/ppa
        update_cache: yes
        state: present

    - name: Install nvidia-drivers
      apt:
        name: nvidia-driver-440
        autoremove: yes
        state: present

    - name: Reboot
      reboot:

    - name: Install nvidia-docker key
      apt_key:
        url: https://nvidia.github.io/nvidia-docker/gpgkey
        state: present
    - name: Add nvidia-docker apt repository
      apt_repository:
        repo: https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list
        state: present
        filename: nvidia-docker
    - name: Install nvidia-docker runtime
      apt:
        name: nvidia-container-toolkit
        update_cache: yes
    - name: Restart the docker service
      service:
        name: docker
        state: restarted

    - name: Add a Jenkins user
      user:
        name: jenkins
        shell: /bin/bash
        groups: docker
        state: present
        create_home: yes
    - name: Add public ssh key for Jenkins access
      authorized_key:
        exclusive: yes
        key: '{{ item }}'
        user: jenkins
        state: present
      with_file:
        - public_keys/jenkins.pub