- hosts: "{{ varhosts | default('amber') }}"
  become: yes
  become_user: root
  tasks:
    - name: 'Update packages'
      apt:
        update_cache: yes
        upgrade: yes
        autoclean: yes
        autoremove: yes

    - name: 'Check if reboot is required'
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: 'Reboot the machine'
      reboot:
      when:
        reboot_required_file.stat.exists
